name: fcm_notification_navigation
description: "A new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.6.10

  # Navigation
  go_router: ^13.2.0

  # Local Notifications
  flutter_local_notifications: ^16.3.0

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true