// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuLaJimooljHbr4nuOUCP8fY3DEqhSiQ',
    appId: '1:1088502375624:web:5d41b728106fbdea89b1fd',
    messagingSenderId: '1088502375624',
    projectId: 'fcm-navigation-demo',
    authDomain: 'fcm-navigation-demo.firebaseapp.com',
    storageBucket: 'fcm-navigation-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBv2OxX2PzsnWAMpCpFkcCIw6sh1z6Uk',
    appId: '1:1088502375624:android:94c1c7edaae4fa3589b1fd',
    messagingSenderId: '1088502375624',
    projectId: 'fcm-navigation-demo',
    storageBucket: 'fcm-navigation-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomU-pxnZIPtccV5oV3SIHs6Rlda8RAfk',
    appId: '1:1088502375624:ios:a6f1f414a5320dff89b1fd',
    messagingSenderId: '1088502375624',
    projectId: 'fcm-navigation-demo',
    storageBucket: 'fcm-navigation-demo.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotificationNavigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAomU-pxnZIPtccV5oV3SIHs6Rlda8RAfk',
    appId: '1:1088502375624:ios:a6f1f414a5320dff89b1fd',
    messagingSenderId: '1088502375624',
    projectId: 'fcm-navigation-demo',
    storageBucket: 'fcm-navigation-demo.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotificationNavigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGuLaJimooljHbr4nuOUCP8fY3DEqhSiQ',
    appId: '1:1088502375624:web:5f5b9dc55cfe119689b1fd',
    messagingSenderId: '1088502375624',
    projectId: 'fcm-navigation-demo',
    authDomain: 'fcm-navigation-demo.firebaseapp.com',
    storageBucket: 'fcm-navigation-demo.firebasestorage.app',
  );
}
